import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import eslintConfigPrettier from "eslint-config-prettier";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  eslintConfigPrettier,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Source-mapped build used by `pnpm lighthouse`.
    ".next-lighthouse/**",
    // The Sanity Studio is its own npm package with its own toolchain.
    "studio/**",
    // Generated by the eve agent runtime (dev cache and build output).
    ".eve/**",
    ".output/**",
  ]),
]);

export default eslintConfig;
